version: '3.4'
services:
  fraud-dashboard:
    image: docker.io/edsandovalhz/fraud-dashboard
    ports: 
    - "8501:8501"
    environment:
    - HZ_ONNX=<hazelcast_ip:port>
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 8Gb
  