version: '3.4'
services:
  hazelcast-onnx:
    image: docker.io/edsandovalhz/hazelcast-onnx
    ports:
      - "5701:5701"
    environment:
      - HAZELCAST_CONFIG=/opt/hazelcast/hazelcast.yml
    deploy:
      resources:
        limits:
          cpus: '4'
        reservations:
          cpus: '4'
  