version: '3.4'
services:
  hazelcast-onnx:
    #image: fraud-detection-onnx-hazelcast-onnx
    #image: docker.io/edsandovalhz/hazelcast-onnx
    #image: docker.io/edsandovalhz/hz-onnx-awsecs
    image: docker.io/edsandovalhz/hz-onnx-all
    ports:
      - "5701:5701"
    environment:
      # For deployment to AWS ECS (via docker compose)
      - HAZELCAST_CONFIG=/opt/hazelcast/hazelcast-aws.yml
    deploy:
      resources:
        limits:
          cpus: '8'
          memory: 16Gb
  
  fraud-dashboard:
    image: docker.io/edsandovalhz/fraud-dashboard
    ports: 
    - "8501:8501"
    environment:
    - HZ_ONNX=hazelcast-onnx:5701
   
  management-center:
    image: hazelcast/management-center:5.2.1
    ports:
    - "8080:8080"
    environment:
    - MC_DEFAULT_CLUSTER=dev
    - MC_DEFAULT_CLUSTER_MEMBERS=hazelcast-onnx
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 4Gb
  
