name: py38-onnx
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - conda-forge::libblas
  - conda-forge::libcblas
  - conda-forge::jupyterlab
  - conda-forge::skl2onnx
  - conda-forge::scipy
  - conda-forge::onnxmltools
  - conda-forge::onnxconverter-common
  - conda-forge::lightgbm
  - conda-forge::zlib=1.2.13
  - conda-forge::ipykernel
  - conda-forge::python_abi
  - conda-forge::pandas
  - pip
  - pip:
    - protobuf
    - numpy
    - typing-extensions
    - pip
